const villainArray = [
	"Agricultural Devastation - Blight",
	"Agricultural Devastation - Crop Failure",
	"Agricultural Devastation - Drought",
	"Agricultural Devastation - Famine",
	"Assualt or Beatings",
	"Bounty Hunting",
	"Assassination",
	"Captivity - Slavery",
	"Captivity - Shackling",
	"Captivity - Imprisonment",
	"Captivity - Kidnapping",
	"Coercion - Bribery",
	"Coercion - Enticement",
	"Coercion - Eviction",
	"Coercion - Legal Intimidation",
	"Coercion - Press Gangs",
	"Coercion - Threats",
	"Coercion - Harassment",
	"Confidence Scams - Breach of Contract",
	"Confidence Scams - Cheating",
	"Confidence Scams - Fast Talking",
	"Confidence Scams - Fine Print",
	"Confidence Scams - Fraud",
	"Confidence Scams - Swindeling",
	"Confidence Scams - Quackery",
	"Confidence Scams - Tricks",
	"Defamation - Framing",
	"Defamation - Gossiping",
	"Defamation - Humiliation",
	"Defamation - Insults",
	"Defamation - Libel",
	"Defamation - Slander",
	"Dueling",
	"Execution - Beheading",
	"Execution - Burning at the Stake",
	"Execution - Burying Alive",
	"Execution - Crucifixtion",
	"Execution - Drawing and Quartering",
	"Execution - Hanging",
	"Execution - Impalement",
	"Execution - Sacrifice",
	"Impersonation or Disguise",
	"Lying or Perjury",
	"Magical Mayhemi - Hauntings",
	"Magical Mayhemi - Illusions",
	"Magical Mayhemi - Infernal Bargains",
	"Magical Mayhemi - Mind Control",
	"Magical Mayhemi - Petrification",
	"Magical Mayhemi - Rasining or Animating the Dead",
	"Magical Mayhemi - Summoning Monsters",
	"Magical Mayhemi - Weather Control",
	"Murder - Assassination",
	"Murder - Cannibalism",
	"Murder - Dismemberment",
	"Murder - Drowning",
	"Murder - Electrocution",
	"Murder - Euthenasia (Involentary)",
	"Murder - Disease",
	"Murder - Poisening",
	"Murder - Stabbing",
	"Murder - Strangulation or Suffocation",
	"Neglect - Family",
	"Neglect - Friends",
	"Neglect - Subjects",
	"Politics - Betrayal or Treason",
	"Politics - Conspiracy",
	"Politics - Espionage or Spying",
	"Politics - Genocide",
	"Politics - Oppression",
	"Politics - Personal Spending of Tax Money",
	"Religion - Curses",
	"Religion - Desecration",
	"Religion - False Gods",
	"Religion - Heresay",
	"Religion - Cults",
	"Stalking",
	"Theft - Burglary",
	"Theft - Blackmail or Extortion",
	"Theft - Counterfitting",
	"Theft - Highway Robbery",
	"Theft - Pickpocketing",
	"Theft - Looting",
	"Theft - Mugging",
	"Theft - Poaching",
	"Theft - Smuggling",
	"Property Crime - Arson",
	"Property Crime - Insurence Fraud",
	"Property Crime - Seizing Property",
	"Torture - Acid",
	"Torture - Blinding",
	"Torture - Branding",
	"Torture - Racking",
	"Torture - Thumbscrews",
	"Torture - Whipping",
	"Vice - Adultery",
	"Vice - Drugs or Alcohol",
	"Vice - Gambling",
	"Vice - Seduction",
	"Warfare - Ambush",
	"Warfare - Invasion",
	"Warfare - Massacre",
	"Warfare - Mercenaries",
	"Warfare - Rebellion",
	"Warfare - Terrorism",
]
const villainButton = document.querySelector("button");
const villainMethodText = document.querySelector(".villainMethodText");
villainButton.addEventListener("click",function(){
	let res = Math.floor(Math.random()*villainArray.length);
	villainMethodText.innerText = villainArray[res];
})